/* Generated automatically by H5make_libsettings -- do not edit */



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright by The HDF Group.                                               *
 * Copyright by the Board of Trustees of the University of Illinois.         *
 * All rights reserved.                                                      *
 *                                                                           *
 * This file is part of HDF5.  The full HDF5 copyright notice, including     *
 * terms governing use, modification, and redistribution, is contained in    *
 * the files COPYING and Copyright.html.  COPYING can be found at the root   *
 * of the source code distribution tree; Copyright.html can be found at the  *
 * root level of an installed copy of the electronic HDF5 document set and   *
 * is linked from the top-level documents page.  It can also be found at     *
 * http://hdfgroup.org/HDF5/doc/Copyright.html.  If you do not have          *
 * access to either file, you may request a copy from help@hdfgroup.org.     *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 * Created:		Sep 28, 2015
 *			wrobell@greymatter
 *
 * Purpose:		This machine-generated source code contains
 *			information about the library build configuration
 *
 * Modifications:
 *
 *	DO NOT MAKE MODIFICATIONS TO THIS FILE!
 *	It was generated by code in `H5make_libsettings.c'.
 *
 *-------------------------------------------------------------------------
 */

char H5libhdf5_settings[]=
	"	    SUMMARY OF THE HDF5 CONFIGURATION\n"
	"	    =================================\n"
	"\n"
	"General Information:\n"
	"-------------------\n"
	"		   HDF5 Version: 1.8.15-patch1\n"
	"		  Configured on: Mon Sep 28 19:45:13 IST 2015\n"
	"		  Configured by: wrobell@greymatter\n"
	"		 Configure mode: production\n"
	"		    Host system: x86_64-unknown-linux-gnu\n"
	"	      Uname information: Linux greymatter 4.1.6-1-ARCH #1 SMP PREEMPT Mon Aug 17 08:52:28 CEST 2015 x86_64 GNU/Linux\n"
	"		       Byte sex: little-endian\n"
	"		      Libraries: static, shared\n"
	"	     Installation point: /home/wrobell/projects/dcmod-os/hdf5-1.8.15-patch1/hdf5\n"
	"\n"
	"Compiling Options:\n"
	"------------------\n"
	"               Compilation Mode: production\n"
	"                     C Compiler: /usr/bin/gcc ( gcc (GCC) 5.2.0)\n"
	"                         CFLAGS: \n"
	"                      H5_CFLAGS:   -ansi -pedantic -Wall -W -Wundef -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wcast-align -Wwrite-strings -Wconversion -Waggregate-return -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wnested-externs -Winline -O -fomit-frame-pointer -finline-functions\n"
	"                      AM_CFLAGS: \n"
	"                       CPPFLAGS: \n"
	"                    H5_CPPFLAGS: -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_GNU_SOURCE -D_POSIX_C_SOURCE=200112L   -DNDEBUG -UH5_DEBUG_API\n"
	"                    AM_CPPFLAGS: -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE \n"
	"               Shared C Library: yes\n"
	"               Static C Library: yes\n"
	"  Statically Linked Executables: no\n"
	"                        LDFLAGS: \n"
	"                     H5_LDFLAGS: \n"
	"                     AM_LDFLAGS: \n"
	" 	 	Extra libraries: -lz -ldl -lm \n"
	" 		       Archiver: ar\n"
	" 		 	 Ranlib: ranlib\n"
	" 	      Debugged Packages: \n"
	"		    API Tracing: no\n"
	"\n"
	"Languages:\n"
	"----------\n"
	"                        Fortran: no\n"
	"\n"
	"                            C++: no\n"
	"\n"
	"Features:\n"
	"---------\n"
	"                  Parallel HDF5: no\n"
	"             High Level library: yes\n"
	"                   Threadsafety: no\n"
	"            Default API Mapping: v18\n"
	" With Deprecated Public Symbols: yes\n"
	"         I/O filters (external): deflate(zlib)\n"
	"                            MPE: no\n"
	"                     Direct VFD: no\n"
	"                        dmalloc: no\n"
	"Clear file buffers before write: yes\n"
	"           Using memory checker: no\n"
	"         Function Stack Tracing: no\n"
	"      Strict File Format Checks: no\n"
	"   Optimization Instrumentation: no\n"
;

